version: '3.8'

services:
  backend:
    build:
      args:
        user: backend
        uid: 1000
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: task_be
      DB_USERNAME: root
      DB_PASSWORD: password
    container_name: task-be
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ./:/var/www/backend
    networks:
      - task_be
    ports:
      - 8002:8002
  db:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: 'task_be'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    volumes:
      - .dbdata:/var/lib/mysql/
    restart: unless-stopped
    networks:
      - task_be
networks:
  task_be:
    driver: bridge
